//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Rocketin.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_movie
    {
        public int id_movie { get; set; }
        public string title { get; set; }
        public string desciption { get; set; }
        public Nullable<int> duration { get; set; }
        public string artist { get; set; }
        public string genres { get; set; }
        public string watch_url { get; set; }
        public Nullable<int> views { get; set; }
    }
}
